---
- name: Create New Store in NetBox
  connection: local
  hosts: localhost
  collections:
    - netbox.netbox
  gather_facts: false

  vars:
    nb_url: https://netbox.cap-butikker.dk
    nb_token: 0c9af3f67783d386bcf43f24b1b84998b7549d5d
    store_site: '{{ store_tbf }}-{{ store_id }}'

  tasks:

    - name: Install requirements in VENV
      pip:
        name: pynetbox

    - name: Create Site obj
      netbox_site:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          name: '{{ store_site }}'
          tags:
            - Butik
        state: present

    - name: Create vlan group
      netbox_vlan_group:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          name: '{{ store_site }}_VLANS'
          site: '{{ store_site }}'
        state: present
      register: store_vlan_grp

    - name: Create vlan 10
      netbox_vlan:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          name: 'MGMT'
          vid: 10
          site: '{{ store_site }}'
          vlan_group: '{{ store_vlan_grp.vlan_group.name }}'
        state: present

    - name: Create vlan 30
      netbox_vlan:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          name: 'CLIENT'
          vid: 30
          site: '{{ store_site }}'
          vlan_group: '{{ store_vlan_grp.vlan_group.name }}'
        state: present

    - name: Create vlan 40
      netbox_vlan:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          name: 'GUEST'
          vid: 40
          site: '{{ store_site }}'
          vlan_group: '{{ store_vlan_grp.vlan_group.name }}'
        state: present

    - name: Create vlan 777
      netbox_vlan:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          name: 'NATIVE'
          vid: 777
          site: '{{ store_site }}'
          vlan_group: '{{ store_vlan_grp.vlan_group.name }}'
        state: present

    - name: Create vlan 999
      netbox_vlan:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          name: 'PARKING_LOT'
          vid: 999
          site: '{{ store_site }}'
          vlan_group: '{{ store_vlan_grp.vlan_group.name }}'
        state: present

    - name: Create Store-prefix
      netbox_prefix:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          parent: 10.64.0.0/10
          prefix_length: 21
          site: '{{ store_site }}'
          status: 'Container'
        state: present
        first_available: yes
      register: store_prefix

    - name: Create MGMT-VLAN prefix
      netbox_prefix:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          parent: '{{ store_prefix.prefix.prefix }}'
          prefix_length: 24
          site: '{{ store_site }}'
          status: Active
          vlan:
            name: 'MGMT'
            vlan_group: '{{ store_vlan_grp.vlan_group.name }}'
        state: present
        first_available: yes
      register: store_MGMT_prefix

    - name: Create CLIENT-VLAN prefix
      netbox_prefix:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          parent: '{{ store_prefix.prefix.prefix }}'
          prefix_length: 23
          site: '{{ store_site }}'
          status: Active
          vlan:
            name: 'CLIENT'
            vlan_group: '{{ store_vlan_grp.vlan_group.name }}'
        state: present
        first_available: yes
      register: store_CLIENT_prefix

    - name: Create GUEST-VLAN prefix
      netbox_prefix:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          parent: '{{ store_prefix.prefix.prefix }}'
          prefix_length: 23
          site: '{{ store_site }}'
          status: Active
          vlan:
            name: 'GUEST'
            vlan_group: '{{ store_vlan_grp.vlan_group.name }}'
        state: present
        first_available: yes
      register: store_GUEST_prefix

    - name: Create router-device
      netbox_device:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          name: '{{ store_site }}-RT01'
          device_type: 2921k9
          device_role: router
          platform: ios
          site: '{{ store_site }}'
        state: present
      register: store_device_RT

    - name: Add description on LAN-interface for Router-device
      netbox_device_interface:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          device: '{{ store_device_RT.device.name }}'
          name: 'GigabitEthernet 0/0'
          description: LAN
        state: present

    - name: Add description on WAN-interface for Router-device
      netbox_device_interface:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          device: '{{ store_device_RT.device.name }}'
          name: 'GigabitEthernet 0/1'
          description: WAN
        state: present

    - name: Add description on MPLS-interface for Router-device
      netbox_device_interface:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          device: '{{ store_device_RT.device.name }}'
          name: 'GigabitEthernet 0/2'
          description: MPLS
        state: present

    - name: Create MGMT subinterface for LAN interface
      netbox_device_interface:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          device: '{{ store_device_RT.device.name }}'
          name: 'GigabitEthernet 0/0.10'
          type: 'Virtual'
          enabled: yes
          mode: Tagged
          tagged_vlans:
            - name: MGMT
              site: '{{ store_site }}'
        state: present
      register: store_device_RT_MGMT_subint

    - name: Create CLIENT subinterface for LAN interface
      netbox_device_interface:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          device: '{{ store_device_RT.device.name }}'
          name: 'GigabitEthernet 0/0.30'
          type: 'Virtual'
          enabled: yes
          mode: Tagged
          tagged_vlans:
            - name: CLIENT
              site: '{{ store_site }}'
        state: present
      register: store_device_RT_CLIENT_subint

    - name: Create GUEST subinterface for LAN interface
      netbox_device_interface:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          device: '{{ store_device_RT.device.name }}'
          name: 'GigabitEthernet 0/0.40'
          type: 'Virtual'
          enabled: yes
          mode: Tagged
          tagged_vlans:
            - name: GUEST
              site: '{{ store_site }}'
        state: present
      register: store_device_RT_GUEST_subint

    - name: Assign IP-address for MGMT subinterface
      netbox_ip_address:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          prefix: '{{ store_MGMT_prefix.prefix.prefix }}'
          assigned_object:
            name: '{{ store_device_RT_MGMT_subint.interface.name }}'
            device: '{{ store_device_RT.device.name }}'
        state: present
      register: store_device_RT_MGMT_ipaddr

    - name: Assign IP-address for CLIENT subinterface
      netbox_ip_address:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          prefix: '{{ store_CLIENT_prefix.prefix.prefix }}'
          assigned_object:
            name: '{{ store_device_RT_CLIENT_subint.interface.name }}'
            device: '{{ store_device_RT.device.name }}'
        state: present
      register: store_device_RT_CLIENT_ipaddr

    - name: Assign IP-address for GUEST subinterface
      netbox_ip_address:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          prefix: '{{ store_GUEST_prefix.prefix.prefix }}'
          assigned_object:
            name: '{{ store_device_RT_GUEST_subint.interface.name }}'
            device: '{{ store_device_RT.device.name }}'
        state: present
      register: store_device_RT_GUEST_ipaddr

    - name: Assign Primary IP-address for Router-device
      netbox_device:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          name: '{{ store_device_RT.device.name }}'
          primary_ip4: '{{ store_device_RT_MGMT_ipaddr.ip_address.address }}'
        state: present

    - name: Create switch-device
      netbox_device:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          name: '{{ store_site }}-SW01'
          device_type: ws-c2960-24pc-l
          device_role: access-switch
          platform: ios
          site: '{{ store_site }}'
        state: present
      register: store_device_SW

    - name: Add description for Uplink-interface for Switch-device
      netbox_device_interface:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          device: '{{ store_device_SW.device.name }}'
          name: 'GigabitEthernet 0/1'
          description: 'UPLINK to {{ store_device_RT.device.name }}'
        state: present

    - name: Create SVI for MGMT
      netbox_device_interface:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          device: '{{ store_device_SW.device.name }}'
          name: 'vlan 10'
          type: 'Virtual'
          enabled: yes
        state: present
      register: store_device_SW_MGMT_SVI

    - name: Create SVI for CLIENT
      netbox_device_interface:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          device: '{{ store_device_SW.device.name }}'
          name: 'vlan 30'
          type: 'Virtual'
          enabled: yes
        state: present
      register: store_device_SW_CLIENT_SVI

    - name: Create SVI for GUEST
      netbox_device_interface:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          device: '{{ store_device_SW.device.name }}'
          name: 'vlan 40'
          type: 'Virtual'
          enabled: yes
        state: present
      register: store_device_SW_GUEST_SVI

    - name: Assign IP-address for MGMT SVI
      netbox_ip_address:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          prefix: '{{ store_MGMT_prefix.prefix.prefix }}'
          assigned_object:
            name: '{{ store_device_SW_MGMT_SVI.interface.name }}'
            device: '{{ store_device_SW.device.name }}'
        state: present
      register: store_device_SW_MGMT_ipaddr

    - name: Assign IP-address for CLIENT SVI
      netbox_ip_address:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          prefix: '{{ store_CLIENT_prefix.prefix.prefix }}'
          assigned_object:
            name: '{{ store_device_SW_CLIENT_SVI.interface.name }}'
            device: '{{ store_device_SW.device.name }}'
        state: present
      register: store_device_SW_CLIENT_ipaddr

    - name: Assign IP-address for GUEST SVI
      netbox_ip_address:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          prefix: '{{ store_GUEST_prefix.prefix.prefix }}'
          assigned_object:
            name: '{{ store_device_SW_GUEST_SVI.interface.name }}'
            device: '{{ store_device_SW.device.name }}'
        state: present
      register: store_device_SW_GUEST_ipaddr

    - name: Assign Primary IP-address for Switch-device
      netbox_device:
        netbox_url: '{{ nb_url }}'
        netbox_token: '{{ nb_token }}'
        data:
          name: '{{ store_device_SW.device.name }}'
          primary_ip4: '{{ store_device_SW_MGMT_ipaddr.ip_address.address }}'
        state: present
...
