---
# Inventory file using module netbox.netbox to gather dynamic inventory from
# NetBox instance for SSoT (Single Source of Truth).
#
# Get all devices within "butikker"

plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox.cap-butikker.dk
token: 0c9af3f67783d386bcf43f24b1b84998b7549d5d
validate_certs: True
config_context: False
group_by:
  - device_roles
  - tags
  - sites
  - platforms

# Do not get devices at HQ or from the staging-setup
query_filter:
  - site__n: 'aar-hq'
  - site__n: 'aar-9999'

# Filter out passive-devices as e.g. patch-panels and only get devices
# with an IP-address
device_query_filters:
  - has_primary_ip: 'true'

# Insert informations as Ansible-facts on hosts
compose:
  ansible_network_os: platform.slug
...
