---
- name: Test connectivity to devices
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:
    - name: Get facts from IOS-devices
      ios_facts:
        gather_subset: all

    - name: Display HOSTNAME and IOS_VERSION
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
...
